# Generated by Django 5.2.11 on 2026-02-24 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(help_text='Format: +639123456789 or 09123456789', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+639XXXXXXXXX' or '09XXXXXXXXX'.", regex='^(?:\\+63|0)9\\d{9}$')])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Only .png and .jpg formats are allowed.', null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
            ],
        ),
    ]
