# Generated by Django 5.2.11 on 2026-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', "Men's Clothing"), ('W', "Women's Clothing"), ('B', 'Beauty'), ('T', 'Technology'), ('A', 'Accessories'), ('H', 'Hair & Body Care'), ('O', 'Other')], max_length=1),
        ),
    ]
